export const typeMovies = {
  "phim-le": "Phim lẻ",
  "phim-moi": "Phim Mới",
  "phim-bo": "Phim Bộ",
  "tv-shows": "TV Shows",
  "hoat-hinh": "Hoạt Hình",
  "phim-vietsub": "Phim Vietsub",
  "phim-thuyet-minh": "Phim Thuyết Minh",
  "phim-long-tieng": "Phim Lồng Tiếng",
  "phim-bo-dang-chieu": "Phim Bộ Đang Chiếu",
  "phim-tron-bo": "Phim Trọn Bộ",
  "phim-sap-chieu": "Phim Sắp Chiếu",
};

export const categoryMovies = {
  "hanh-dong": "Hành Động",
  "tinh-cam": "Tình Cảm",
  "hai-huoc": "Hài Hước",
  "co-trang": "Cổ Trang",
  "tam-ly": "Tâm Lý",
  "hinh-su": "Hình Sự",
  "chien-tranh": "Chiến Tranh",
  "the-thao": "Thể Thao",
  "vo-thuat": "Võ Thuật",
  "vien-tuong": "Viễn Tưởng",
  "khoa-hoc": "Khoa Học",
  "kinh-di": "Kinh Dị",
  "am-nhac": "Âm Nhạc",
  "than-thoai": "Thần Thoại",
  "tai-lieu": "Tài Liệu",
  "gia-dinh": "Gia Đình",
  "chinh-kich": "Chính kịch",
  "bi-an": "Bí ẩn",
  "hoc-duong": "Học Đường",
  "kinh-dien": "Kinh Điển",
  "phieu-luu": "Phiêu Lưu",
};

export const nationMovies = {
  "trung-quoc": "Trung Quốc",
  "han-quoc": "Hàn Quốc",
  "nhat-ban": "Nhật Bản",
  "thai-lan": "Thái Lan",
  "au-my": "Âu Mỹ",
  "dai-loan": "Đài Loan",
  "hong-kong": "Hồng Kông",
  "an-do": "Ấn Độ",
  anh: "Anh",
  phap: "Pháp",
  canada: "Canada",
  "quoc-gia-khac": "Quốc Gia Khác",
  duc: "Đức",
  "tay-ban-nha": "Tây Ban Nha",
  "tho-nhi-ky": "Thổ Nhĩ Kỳ",
  "ha-lan": "Hà Lan",
  indonesia: "Indonesia",
  nga: "Nga",
  mexico: "Mexico",
  uc: "Úc",
  "thuy-dien": "Thụy Điển",
  malaysia: "Malaysia",
  brazil: "Brazil",
  philippines: "Philippines",
  "bo-dao-nha": "Bồ Đào Nha",
  y: "Ý",
  "dan-mach": "Đan Mạch",
  uae: "UAE",
  "na-uy": "Na Uy",
  "thuy-si": "Thụy Sĩ",
  "chau-phi": "Châu Phi",
  "nam-phi": "Nam Phi",
  ukraina: "Ukraina",
  "a-rap-xe-ut": "Ả Rập Xê Út",
  "viet-nam": "Việt Nam",
};

export const timeMovies = {
  2026: "2026",
  2025: "2025",
  2024: "2024",
  2023: "2023",
  2022: "2022",
  2021: "2021",
  2020: "2020",
  2019: "2019",
  2018: "2018",
  2017: "2017",
  2016: "2016",
  2015: "2015",
  2014: "2014",
  2013: "2013",
  2012: "2012",
  2011: "2011",
  2010: "2010",
  2009: "2009",
  2008: "2008",
  2007: "2007",
  2006: "2006",
  2005: "2005",
  2004: "2004",
  2003: "2003",
  2002: "2002",
  2001: "2001",
  2000: "2000",
  1995: "Trước 2000",
};

export const arrangeMovies = {
  "modified.time": "Ngày cập nhật",
  year: "Năm sản xuất",
  view: "Lượt xem",
};
